# Data source paths
data:
  ndjson_dir: exports/ndjson
  issues_dir: exports/issues_ndjson
  videos_dir: ../../../datasets/SelectedVideos_video_segments

# Batch constraints
constraints:
  video_names_file: visualization/video_lists/forward.json
  approver: null
  time_range: null

# Visualization settings
visualization:  
  label: cam_motion.ground_centric_movement.forward.has_forward_wrt_ground

# Server settings
server:
  host: localhost
  port: 8085