# Data source paths
data:
  ndjson_dir: exports/ndjson
  issues_dir: exports/issues_ndjson
  videos_dir: ../../../datasets/SelectedVideos_video_segments

# Batch constraints
constraints:
  video_names_file: visualization/video_lists/donesection.json
  approver: null
  time_range: null

# Visualization settings
visualization:
  lazy_load_videos: true  # New flag to control lazy loading

# Server settings
server:
  host: localhost
  port: 8085